### ISSUE TITLE
Github Actions to build binaries and deploy to releases page

### ISSUE THREAD

**Issue by davelab6** [simoncozens/fontbakery-ui#5]
FB rapidly changes so will be good to keep it fresh

**Comment by simoncozens** [comment]
Perhaps better to have a way to auto-update the app?

**Comment by simoncozens** [comment]
Yanone says:
> Also, instead of implementing an auto-update feature, maybe just have the app check with the fontbakery repo for the existence of a newer version. If the app is indeed built automatically alongside fontbakery, one just needs to compare the version of the bundled fontbakery module with the online one.

I figure maybe having the app run pip (as a library) on launch to test if there is an upgrade available, upgrade its internal copy of qfontbakery, and restart.

**Comment by simoncozens** [comment]
Well, I've added code to prompt the user to update things, but it seems like we're onto a loser here for MacOS.

* py2app comes with its own stripped-down version of site.py (which is required by pip) which doesn't include a `USER_BASE` variable. pip tries to import `USER_BASE` and crashes.
* We can't put updated fontbakery libraries into the app into the app itself, because that will break the code signing.
* So at the very least we need a custom py2app with a sensible `USER_BASE` which copies the logic from the stock Python `_getuserbase` and finds the user home directory, then fiddle with `sys.path` early in the process to look for updated code in the user home directory.

**Comment by simoncozens** [comment]
I don't know if I've fixed auto-updates. However, I *have* sorted out Continuous Deployment, which is the point of this issue.
